export default Object.freeze({
  ADD_ITEM: 'ADD_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  TOGGLE_COMPLETED: 'TOGGLE_COMPLETED',
  COMPLETE_ALL: 'COMPLETE_ALL',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
  CHANGE_FILTER: 'CHANGE_FILTER'
})
